nome = input('Digite seu nome completo: ')
separa = nome.split()
print('Seu nome com todas as letras maiúsculas: {}'.format(nome.upper()))
print('Seu nome completo tem {} letras'.format(len(nome.replace(" ", ""))))
# ou: print('Seu nome completo tem {} letras'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(len(separa[0])))